openapi: 3.1.0
info:
  version: '1.0'
  title: sns-app
  description: SNSアプリ
paths:
  '/users/{handle_name}':
    get:
      tags:
        - Users
      summary: Get User Info
      description: ''
      operationId: getUserByHandleName
      parameters:
        - name: handle_name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
              examples:
                Example 1:
                  value:
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    handle_name: tecsoc
                    display_name: TecSoc
                    encrypted_email_address: aa
                    encrypted_password: bb
        '404':
          description: Not Found
  /users:
    post:
      tags:
        - Users
      summary: Create User
      description: ''
      operationId: postUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
            examples:
              Example 1:
                value:
                  id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                  handle_name: tecsoc
                  display_name: TecSoc
                  encrypted_email_address: aa
                  encrypted_password: bb
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
              examples:
                Example 1:
                  value:
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    handle_name: tecsoc
                    display_name: TecSoc
                    encrypted_email_address: aa
                    encrypted_password: bb
        '400':
          description: Bad Request
tags:
  - name: Users
components:
  schemas:
    Users:
      type: object
      title: Users
      properties:
        id:
          type: string
          format: uuid
          writeOnly: true
        handle_name:
          type: string
        display_name:
          type: string
        encrypted_email_address:
          type: string
          writeOnly: true
        encrypted_password:
          type: string
          writeOnly: true
      required:
        - id
        - handle_name
        - display_name
        - encrypted_email_address
        - encrypted_password